name: dcrs
version: 0.1.0
summary: Web/HTML5 based computing
description: |
  It can be a web "BIOS"
  or it can be a web OS running multiple "OS"

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  dcrs:
    command: desktop-launch $SNAP/dcrs.wrapper
    plugs:
     - browser-support #like how is THIS a thing?
     - network
     - unity7
     - gsettings
     # - home
     # - pulseaudio
     # - opengl
    desktop: dcrs.desktop
  zeronet:
    command: bin/zeronet
    plugs: [network, network-bind]
  ipfs:
    command: bin/ipfs
    plugs: [network, network-bind]

parts:
  dcrs:
    after:
      - deps
      - desktop-integration
      - launcher
      - ipfs
      - zeronet
      - desktop
    source: https://github.com/DCRS/DCRS-UI
    source-type: git
    source-branch: master
    plugin: nodejs
    node-engine: 6.10.2
    node-packages:
     - electron
#deps of dcrs
  desktop:
    source: snap/gui
    plugin: dump

  deps:
    plugin: nil
    stage-packages:
      - libgconf-2-4
      - libnss3
      - libxss1
      - fontconfig-config

  desktop-integration:
    plugin: nil
    stage-packages:
      - libappindicator1
      - libdbusmenu-glib4
      - libnotify4
      - libunity9

  launcher:
    source: snap/scripts
    plugin: dump
    after: [desktop-glib-only]
#ipfs
  ipfs:
    source: https://github.com/ipfs/go-ipfs.git
    source-tag: v0.4.8
    plugin: nil
    build-packages: [make, wget]
    prepare: |
      mkdir -p ../go/src/github.com/ipfs/go-ipfs
      cp -R . ../go/src/github.com/ipfs/go-ipfs
    build: |
      env GOPATH=$(pwd)/../go make -C ../go/src/github.com/ipfs/go-ipfs install
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv ../go/bin/ipfs $SNAPCRAFT_PART_INSTALL/bin/
    after: [go]
  go:
    source-tag: go1.7.5
#zeronet
  zeronet:
    after:
      - zn-source
      - zn-scripts
    prime:
      - usr
      - bin
      - lib
      - include
      - etc
      - -usr/share/doc
      - -usr/share/man
      - -requirements.txt
      - -.gitignore
    source: snap/empty
    plugin: python
    python-version: python2
    requirements: $SNAPCRAFT_STAGE/zeronet/requirements.txt
  zn-scripts:
    source: snap/zn-scripts
    prime:
      - zeronet/*
      - bin/*
    plugin: dump
    prepare: |
      python2 -m py_compile $(find -type f -iname "*.py" -print)
      rm -f $SNAPCRAFT_PART_INSTALL/bin
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      ln -s ../zeronet/launcher.py $SNAPCRAFT_PART_INSTALL/bin/zeronet
  zn-source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-tag: v0.5.4
    source-type: git
    organize:
      src: zeronet/src
      tools: zeronet/tools
      plugins: zeronet/plugins
      zeronet.py: zeronet/zeronet.py
      zeronet.pyc: zeronet/zeronet.pyc
      start.py: zeronet/start.py
      start.pyc: zeronet/start.pyc
      requirements.txt: zeronet/requirements.txt
    prepare: |
      sed 's/self.plugin_path = "plugins"/self.plugin_path = os.environ["SNAP_USER_COMMON"]+"\/zeronet\/plugins"/g' -i src/Plugin/PluginManager.py
      python2 -m py_compile $(find -type f -iname "*.py" -print)
    stage:
      - zeronet/*
    plugin: dump
